// This file is generated by rust-protobuf 2.25.2. Do not edit
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_imports)]
#![allow(unused_results)]
//! Generated file from `balance.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
// const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_2_25_2;

#[derive(PartialEq,Clone,Default)]
pub struct Balance {
    // message fields
    pub address: ::std::string::String,
    pub ts: u64,
    pub blockchain: u32,
    pub asset: ::std::string::String,
    pub amount: ::std::string::String,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a Balance {
    fn default() -> &'a Balance {
        <Balance as ::protobuf::Message>::default_instance()
    }
}

impl Balance {
    pub fn new() -> Balance {
        ::std::default::Default::default()
    }

    // string address = 1;


    pub fn get_address(&self) -> &str {
        &self.address
    }
    pub fn clear_address(&mut self) {
        self.address.clear();
    }

    // Param is passed by value, moved
    pub fn set_address(&mut self, v: ::std::string::String) {
        self.address = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_address(&mut self) -> &mut ::std::string::String {
        &mut self.address
    }

    // Take field
    pub fn take_address(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.address, ::std::string::String::new())
    }

    // uint64 ts = 2;


    pub fn get_ts(&self) -> u64 {
        self.ts
    }
    pub fn clear_ts(&mut self) {
        self.ts = 0;
    }

    // Param is passed by value, moved
    pub fn set_ts(&mut self, v: u64) {
        self.ts = v;
    }

    // uint32 blockchain = 3;


    pub fn get_blockchain(&self) -> u32 {
        self.blockchain
    }
    pub fn clear_blockchain(&mut self) {
        self.blockchain = 0;
    }

    // Param is passed by value, moved
    pub fn set_blockchain(&mut self, v: u32) {
        self.blockchain = v;
    }

    // string asset = 4;


    pub fn get_asset(&self) -> &str {
        &self.asset
    }
    pub fn clear_asset(&mut self) {
        self.asset.clear();
    }

    // Param is passed by value, moved
    pub fn set_asset(&mut self, v: ::std::string::String) {
        self.asset = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_asset(&mut self) -> &mut ::std::string::String {
        &mut self.asset
    }

    // Take field
    pub fn take_asset(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.asset, ::std::string::String::new())
    }

    // string amount = 5;


    pub fn get_amount(&self) -> &str {
        &self.amount
    }
    pub fn clear_amount(&mut self) {
        self.amount.clear();
    }

    // Param is passed by value, moved
    pub fn set_amount(&mut self, v: ::std::string::String) {
        self.amount = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_amount(&mut self) -> &mut ::std::string::String {
        &mut self.amount
    }

    // Take field
    pub fn take_amount(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.amount, ::std::string::String::new())
    }
}

impl ::protobuf::Message for Balance {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.address)?;
                },
                2 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint64()?;
                    self.ts = tmp;
                },
                3 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint32()?;
                    self.blockchain = tmp;
                },
                4 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.asset)?;
                },
                5 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.amount)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if !self.address.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.address);
        }
        if self.ts != 0 {
            my_size += ::protobuf::rt::value_size(2, self.ts, ::protobuf::wire_format::WireTypeVarint);
        }
        if self.blockchain != 0 {
            my_size += ::protobuf::rt::value_size(3, self.blockchain, ::protobuf::wire_format::WireTypeVarint);
        }
        if !self.asset.is_empty() {
            my_size += ::protobuf::rt::string_size(4, &self.asset);
        }
        if !self.amount.is_empty() {
            my_size += ::protobuf::rt::string_size(5, &self.amount);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if !self.address.is_empty() {
            os.write_string(1, &self.address)?;
        }
        if self.ts != 0 {
            os.write_uint64(2, self.ts)?;
        }
        if self.blockchain != 0 {
            os.write_uint32(3, self.blockchain)?;
        }
        if !self.asset.is_empty() {
            os.write_string(4, &self.asset)?;
        }
        if !self.amount.is_empty() {
            os.write_string(5, &self.amount)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> Balance {
        Balance::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                "address",
                |m: &Balance| { &m.address },
                |m: &mut Balance| { &mut m.address },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeUint64>(
                "ts",
                |m: &Balance| { &m.ts },
                |m: &mut Balance| { &mut m.ts },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeUint32>(
                "blockchain",
                |m: &Balance| { &m.blockchain },
                |m: &mut Balance| { &mut m.blockchain },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                "asset",
                |m: &Balance| { &m.asset },
                |m: &mut Balance| { &mut m.asset },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                "amount",
                |m: &Balance| { &m.amount },
                |m: &mut Balance| { &mut m.amount },
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<Balance>(
                "Balance",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static Balance {
        static instance: ::protobuf::rt::LazyV2<Balance> = ::protobuf::rt::LazyV2::INIT;
        instance.get(Balance::new)
    }
}

impl ::protobuf::Clear for Balance {
    fn clear(&mut self) {
        self.address.clear();
        self.ts = 0;
        self.blockchain = 0;
        self.asset.clear();
        self.amount.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for Balance {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for Balance {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct BalanceBundle {
    // message fields
    pub balances: ::protobuf::RepeatedField<Balance>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a BalanceBundle {
    fn default() -> &'a BalanceBundle {
        <BalanceBundle as ::protobuf::Message>::default_instance()
    }
}

impl BalanceBundle {
    pub fn new() -> BalanceBundle {
        ::std::default::Default::default()
    }

    // repeated .emerald.state.Balance balances = 1;


    pub fn get_balances(&self) -> &[Balance] {
        &self.balances
    }
    pub fn clear_balances(&mut self) {
        self.balances.clear();
    }

    // Param is passed by value, moved
    pub fn set_balances(&mut self, v: ::protobuf::RepeatedField<Balance>) {
        self.balances = v;
    }

    // Mutable pointer to the field.
    pub fn mut_balances(&mut self) -> &mut ::protobuf::RepeatedField<Balance> {
        &mut self.balances
    }

    // Take field
    pub fn take_balances(&mut self) -> ::protobuf::RepeatedField<Balance> {
        ::std::mem::replace(&mut self.balances, ::protobuf::RepeatedField::new())
    }
}

impl ::protobuf::Message for BalanceBundle {
    fn is_initialized(&self) -> bool {
        for v in &self.balances {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_repeated_message_into(wire_type, is, &mut self.balances)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        for value in &self.balances {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        };
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        for v in &self.balances {
            os.write_tag(1, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        };
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> BalanceBundle {
        BalanceBundle::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_repeated_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<Balance>>(
                "balances",
                |m: &BalanceBundle| { &m.balances },
                |m: &mut BalanceBundle| { &mut m.balances },
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<BalanceBundle>(
                "BalanceBundle",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static BalanceBundle {
        static instance: ::protobuf::rt::LazyV2<BalanceBundle> = ::protobuf::rt::LazyV2::INIT;
        instance.get(BalanceBundle::new)
    }
}

impl ::protobuf::Clear for BalanceBundle {
    fn clear(&mut self) {
        self.balances.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for BalanceBundle {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for BalanceBundle {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\rbalance.proto\x12\remerald.state\"\x81\x01\n\x07Balance\x12\x18\n\
    \x07address\x18\x01\x20\x01(\tR\x07address\x12\x0e\n\x02ts\x18\x02\x20\
    \x01(\x04R\x02ts\x12\x1e\n\nblockchain\x18\x03\x20\x01(\rR\nblockchain\
    \x12\x14\n\x05asset\x18\x04\x20\x01(\tR\x05asset\x12\x16\n\x06amount\x18\
    \x05\x20\x01(\tR\x06amount\"C\n\rBalanceBundle\x122\n\x08balances\x18\
    \x01\x20\x03(\x0b2\x16.emerald.state.BalanceR\x08balancesJ\xa4\x03\n\x06\
    \x12\x04\0\0\r\x01\n\x08\n\x01\x0c\x12\x03\0\0\x12\n\x08\n\x01\x02\x12\
    \x03\x01\0\x16\n\n\n\x02\x04\0\x12\x04\x03\0\t\x01\n\n\n\x03\x04\0\x01\
    \x12\x03\x03\x08\x0f\n\x0b\n\x04\x04\0\x02\0\x12\x03\x04\x02\x15\n\x0c\n\
    \x05\x04\0\x02\0\x05\x12\x03\x04\x02\x08\n\x0c\n\x05\x04\0\x02\0\x01\x12\
    \x03\x04\t\x10\n\x0c\n\x05\x04\0\x02\0\x03\x12\x03\x04\x13\x14\n\x0b\n\
    \x04\x04\0\x02\x01\x12\x03\x05\x02\x10\n\x0c\n\x05\x04\0\x02\x01\x05\x12\
    \x03\x05\x02\x08\n\x0c\n\x05\x04\0\x02\x01\x01\x12\x03\x05\t\x0b\n\x0c\n\
    \x05\x04\0\x02\x01\x03\x12\x03\x05\x0e\x0f\n\x0b\n\x04\x04\0\x02\x02\x12\
    \x03\x06\x02\x18\n\x0c\n\x05\x04\0\x02\x02\x05\x12\x03\x06\x02\x08\n\x0c\
    \n\x05\x04\0\x02\x02\x01\x12\x03\x06\t\x13\n\x0c\n\x05\x04\0\x02\x02\x03\
    \x12\x03\x06\x16\x17\n\x0b\n\x04\x04\0\x02\x03\x12\x03\x07\x02\x13\n\x0c\
    \n\x05\x04\0\x02\x03\x05\x12\x03\x07\x02\x08\n\x0c\n\x05\x04\0\x02\x03\
    \x01\x12\x03\x07\t\x0e\n\x0c\n\x05\x04\0\x02\x03\x03\x12\x03\x07\x11\x12\
    \n\x0b\n\x04\x04\0\x02\x04\x12\x03\x08\x02\x14\n\x0c\n\x05\x04\0\x02\x04\
    \x05\x12\x03\x08\x02\x08\n\x0c\n\x05\x04\0\x02\x04\x01\x12\x03\x08\t\x0f\
    \n\x0c\n\x05\x04\0\x02\x04\x03\x12\x03\x08\x12\x13\n\n\n\x02\x04\x01\x12\
    \x04\x0b\0\r\x01\n\n\n\x03\x04\x01\x01\x12\x03\x0b\x08\x15\n\x0b\n\x04\
    \x04\x01\x02\0\x12\x03\x0c\x02\x20\n\x0c\n\x05\x04\x01\x02\0\x04\x12\x03\
    \x0c\x02\n\n\x0c\n\x05\x04\x01\x02\0\x06\x12\x03\x0c\x0b\x12\n\x0c\n\x05\
    \x04\x01\x02\0\x01\x12\x03\x0c\x13\x1b\n\x0c\n\x05\x04\x01\x02\0\x03\x12\
    \x03\x0c\x1e\x1fb\x06proto3\
";

static file_descriptor_proto_lazy: ::protobuf::rt::LazyV2<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::LazyV2::INIT;

fn parse_descriptor_proto() -> ::protobuf::descriptor::FileDescriptorProto {
    ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
}

pub fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    file_descriptor_proto_lazy.get(|| {
        parse_descriptor_proto()
    })
}
